routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('order.create');
});

Route::get('order/create', 'OrderController@create')->name('order.create');
Route::post('order', 'OrderController@store')->name('order.store');

Route::get('statistics', 'SalesStatisticsController@index')->name('statistics.index');
Route::get('statistics/getData', 'SalesStatisticsController@getData')->name('statistics.getData');

Route::resources([
    'categories' => 'CategoryController',
    'products' => 'ProductController'
]);

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        
        <title>Test task</title>

        <!-- Fonts -->

        <!-- Styles -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
        
        @stack('styles')

        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
        @stack('scripts')

    </head>
    <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Test task</a>
    </nav>

        <div class="container-fluid">
            <div class="row">
                @section('sidebar')
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('order.create') }}">
                                <span data-feather="shopping-cart"></span>
                                Order
                                </a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{{ route('categories.index') }}">
                                <span data-feather="file"></span>
                                Categories
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('products.index') }}">
                                <span data-feather="shopping-cart"></span>
                                Products
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('statistics.index') }}">
                                <span data-feather="home"></span>
                                Statistics
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                @show

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-top: 10px">
                    @yield('content')
                </main>
            </div>
        </div>
        <script>
            /**
             * Delete row from table
             */
            function deleteRow(event) {
                $(event.target).parent().parent().remove();
            }
        </script>
    </body>
</html>