routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('order.create');
});

Route::get('order/create', 'OrderController@create')->name('order.create');
Route::post('order', 'OrderController@store')->name('order.store');

Route::get('statistics', 'SalesStatisticsController@index')->name('statistics.index');
Route::get('statistics/getData', 'SalesStatisticsController@getData')->name('statistics.getData');

Route::resources([
    'categories' => 'CategoryController',
    'products' => 'ProductController'
]);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    /**
     * Get the products associated with the category
     */
    public function products()
    {
        return $this->hasMany('App\Models\Product');
    }

    /**
     * Get the orders associated with the category
     */
    public function orders()
    {
        return $this->hasMany('App\Models\Order');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category.index', ['categories' => Category::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);
        $category = new Category($request->only('name'));
        $category->save();

        $request->session()->flash('message', 'Category has been created.');
        return redirect()->action('CategoryController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);
        $category = Category::findOrFail($id);
        $category->name = $request->input('name');
        $category->save();

        $request->session()->flash('message', 'Category has been updated.');
        return redirect()->action('CategoryController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
    }
}

resources/views/category/create.blade.php
@extends('base')

@section('content')
<h2>Create category</h2>
<form action="{{ route('categories.store') }}" method="POST">
    @csrf
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" id="name" name="name" required>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
@endsection

resources/views/category/edit.blade.php
@extends('base')

@section('content')
<h2>Edit category</h2>
<form action="{{ route('categories.update', ['id' => $category->id]) }}" method="POST">
    @method('PUT')
    @csrf
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" id="name" name="name" value="{{ $category->name }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
@endsection

resources/views/category/index.blade.php
@extends('base')

@section('content')

@if (Session::has('message'))
  <div class="alert alert-success" role="alert">
    {!! session('message') !!}
  </div>
@endif

<div class="d-flex justify-content-between">
    <div><h2>Categories</h2></div>
    <div>
        <a href=" {{ route('categories.create') }}">
            <button type="button" class="btn btn-primary">Add category</button>
        </a>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          @foreach ($categories as $category)
                <tr>
                  <td>{{ $category->id }}</td>
                  <td>{{ $category->name }}</td>
                  <td>
                    <a href="{{ route('categories.edit', ['id' => $category->id])}}">
                      <button class="btn btn-info btn-sm">Edit</button>
                    </a>
                  </td>
                  <td>
                    <button data-id="{{ $category->id }}" data-href="{{ route('categories.destroy', ['id' => '_ID_']) }}" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                  </td>
                <tr>
          @endforeach
      </tbody>
    </table>
</div>

<script>
    function deleteCategory(event) { 
        let data = event.target.dataset;
        let isConfirm = confirm("Are you sure you want to delete this category?");

        if (isConfirm) {
            $.ajax({
                url: data.href.replace('_ID_', data.id),
                method: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function() {
                    deleteRow(event);
                },
                error: function() {
                    alert( "An error occured" );
                },
            })
        }   
    }

    $('.btn-danger').click(deleteCategory); 
</script>
@endsection